# This is a basic workflow to help you get started with Actions

name: Streams

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git pull
          git config --global user.email "naveen.land4@gmail.com"
          git config --global user.name "naveen.land4"

      - name: update streams
        run: |
          pwd
          python3 index.py "https://www.youtube.com/channel/UCtbo6_eDG7zEtaOtcSltJkA/live" > NewsTamil24x7.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/channel/UC8Z-VjXBtDJTvq6aqkIskPg/live" > PolimerNews.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/watch?v=NX18e_Wh7NA/live" > PuthiyaThalaimurai.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/channel/UCJN51JyuwzL1Npd-mEYGLHA/live" > MNaduNews.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/channel/UC2ziCMHFPWkFHjocUMXT__Q/live" > SathiyamTV.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/watch?v=FeweQREkl44/live" > ThanthiTV.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/channel/UCXbufH95DIUqyAWSzeDI0JQ/live" > MalaimurasuTv.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/channel/UCYlh4lH762HvHt6mmiecyWQ/live" > SunNews.m3u8
          sleep 15
          python3 index.py "https://www.youtube.com/watch?v=mQrZJFyYzlI/live" > News18TamilNadu.m3u8

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "Update streams"
          git push
